### ISSUE TITLE
生成的相对路径错误

### ISSUE THREAD

**Issue by Zhou-Tx** [long-woo/stc#38]
当`tag`中存在`/`时，会生成多级目录，但`import`时使用的相对路径仍然是在当前目录`./`。
![image](https://github.com/long-woo/stc/assets/54386692/56b2a7d1-4576-4c92-b70d-382555b85641)

**Comment by long-woo** [comment]
下个版本修复

**Comment by Zhou-Tx** [comment]
我已收到你发的邮件，谢谢
